apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-auth-external-secret
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mongodb-secret-store
    kind: SecretStore
  target:
    name: mongodb-auth
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: mongodb/hp-bootstrap/prod
        property: MONGO_ROOT_PASSWORD
