apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: mongodb-secret-store
  namespace: mongodb
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: mongodb-secrets-sa
