apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: sonarqube-db-store # 상점 이름
  namespace: cicd          # 소나큐브가 있는 네임스페이스
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2