# [Common] 모든 환경 공통 설정
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: HomePlate

  # 1. 구글 로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_ID}
            client-secret: ${OAUTH_SECRET}
            scope:
              - email
              - profile

  # 2. 이메일 설정
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # 3. Kafka 공통 설정
  kafka:
    consumer:
      group-id: ticketing-notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # 4. JPA 공통 기본값 (운영 기준: 로그 끔, ddl-auto: validate 추천)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # 기본은 검증만 (Local에서 update로 덮어씀)
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect # Dialect 명시

# 5. Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

# 6. JWT 설정
jwt:
  secret: ${JWT_KEY}
  accessTokenExt: 3600000
  refreshTokenExt: 604800000

# 7. 외부 API
api:
  weather:
    key: ${WEATHER_API_KEY}
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst

# 8. 모니터링
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true