apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-hp-infra__cert-manager__hp-cert-manager-ops
  namespace: cert-manager
subjects:
  - kind: Group
    name: hp-infra
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: hp-cert-manager-ops
  apiGroup: rbac.authorization.k8s.io
