apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-webhook-external-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd-aws-store
    kind: SecretStore
  target:
    name: argocd-secret # 👈 기존 아르고CD 시크릿 이름을 지정
    creationPolicy: Merge # 👈 중요! 기존 데이터를 유지하고 새 값만 합칩니다.
    deletionPolicy: Retain
  data:
  - secretKey: webhook.github.secret # 👈 아르고CD가 웹훅 비밀번호로 인식하는 키 이름
    remoteRef:
      key: prod/argocd/webhook # AWS에 저장한 이름
      property: webhook-secret # AWS에 저장한 키 이름