apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hp-kyverno-operation-policy-admin
rules:
  - apiGroups: ["kyverno.io"]
    resources: ["policies"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["wgpolicyk8s.io"]
    resources: ["policyreports","clusterpolicyreports"]
    verbs: ["get","list","watch"]
