apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
  annotations:
    # SecretStore 다음으로 생성되어야 합니다.
    # Keycloak Pod 시작 전에 Secret이 반드시 존재해야 합니다.
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: keycloak-secret-store
    kind: SecretStore

  target:
    name: keycloak-secrets  # 생성될 Kubernetes Secret 이름
    creationPolicy: Owner   # ExternalSecret 삭제 시 Secret도 같이 삭제

  data:
    - secretKey: db-password
      remoteRef:
        key: keycloak/rds/master/prod
        property: password

    - secretKey: admin-password
      remoteRef:
        key: keycloak/admin/prod
        property: password
