apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: keycloak-secret-store
  namespace: keycloak
  annotations:
    # Service Account 다음으로 생성되어야 합니다.
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: keycloak-external-secrets-sa
