apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: hp-frontend-secret-store # 이 이름은 front-external-secret.yaml에서 참조함
  namespace: hp-core             # 프론트엔드와 같은 동네!
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: hp-frontend-sa # 프론트엔드 전용 신분증 사용