apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hp-frontend-external-secret  # ExternalSecret 리소스 이름
  namespace: hp-core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hp-frontend-secret-store # 아까 만든 SecretStore 재사용 (리전/인증 정보 동일)
    kind: SecretStore
  target:
    name: hp-frontend-secret     # ⭐ 여기가 중요! Deployment의 envFrom에서 찾던 그 이름입니다.
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: prod/hp-frontend/env  # AWS Secrets Manager에 저장된 시크릿 이름