apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-sync-writer
  namespace: hp-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-sync-writer
subjects:
- kind: ServiceAccount
  name: secret-sync-sa
  namespace: hp-core
