apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-sync-writer
  namespace: hp-core
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - list
