apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-kafkauser-secrets
  namespace: hp-core
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata: {}
    spec:
      backoffLimit: 2
      template:
        metadata: 
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - args:
            - |
              set -eu

              SRC_NS="kafka"
              DST_NS="hp-core"

              SECRETS="
              ticketing-cluster-ca-cert
              ticketing-notification-client
              "

              for NAME in $SECRETS; do
                echo "----------------------------------------"
                echo "Syncing: $NAME"

                if ! kubectl -n "$SRC_NS" get secret "$NAME" >/dev/null 2>&1; then
                  echo "WARN: $NAME not found in $SRC_NS, skip"
                  continue
                fi

                kubectl -n "$SRC_NS" get secret "$NAME" -o json \
                  | jq --arg ns "$DST_NS" '
                      .metadata.namespace = $ns
                      | del(
                          .metadata.uid,
                          .metadata.resourceVersion,
                          .metadata.creationTimestamp,
                          .metadata.managedFields,
                          .metadata.ownerReferences
                        )
                    ' \
                  | kubectl -n "$DST_NS" apply -f -

                echo "OK: $NAME synced"
              done

              echo "Done."
            command:
            - /bin/sh
            - -c
            image: 681224237958.dkr.ecr.ap-northeast-2.amazonaws.com/kubectl-openssl:v0.1.9
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
            imagePullPolicy: IfNotPresent
            name: sync
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          nodeSelector:
            nodepool: app
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          serviceAccount: secret-sync-sa
          serviceAccountName: secret-sync-sa
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 1
  suspend: false
