apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hp-backend-external-secret
  namespace: hp-core
spec:
  refreshInterval: 1h             # 1시간마다 AWS와 동기화 (값이 바뀌면 자동 반영)
  secretStoreRef:
    name: hp-backend-store
    kind: SecretStore
  target:
    name: hp-backend-secret       # 👈 쿠버네티스에서 생성될 시크릿 이름
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: prod/hp-backend/env    # 👈 AWS Secrets Manager에 저장한 이름