apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hp-app-secret
  namespace: hp-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hp-workers-secret-store
    kind: SecretStore
  target:
    name: hp-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mongodb/hp-app/prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hp-exporter-secret
  namespace: hp-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hp-workers-secret-store
    kind: SecretStore
  target:
    name: hp-exporter-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mongodb/hp-exporter/prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hp-bootstrap-secret
  namespace: hp-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hp-workers-secret-store
    kind: SecretStore
  target:
    name: hp-bootstrap-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mongodb/hp-bootstrap/prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hp-rds-secret
  namespace: hp-workers
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hp-workers-secret-store
    kind: SecretStore
  target:
    name: hp-rds-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rds/hp-app/prod
