apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: hp-workers-secret-store
  namespace: hp-workers
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: hp-workers-eso-sa
