apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-hp-sre__ops-databases__hp-workload-admin
  namespace: ops-databases
subjects:
  - kind: Group
    name: hp-sre
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: hp-workload-admin
  apiGroup: rbac.authorization.k8s.io

